[tool.poetry]
name = "soccertrack"
version = "0.1.0"
description = "A dataset and algorithm for multi-object tracking in sports"
authors = ["Atom Scott <atom.james.scott@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
omegaconf = "^2.2.2"
pytest = "^7.1.2"
ffmpeg-python = "^0.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
