[tool.poetry]
name = "soccertrack"
version = "0.1.0"
description = "A dataset and algorithm for multi-object tracking in sports"
authors = ["Atom Scott <atom.james.scott@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
omegaconf = "^2.2.2"
pytest = "^7.1.2"
ffmpeg-python = "^0.2.0"
numpy = "^1.22.4"
pandas = "^1.4.2"
opencv-python = "^4.5.5"
matplotlib = "^3.5.2"
pysrt = "^1.1.2"
loguru = "^0.6.0"
rich = "^12.4.4"
tqdm = "^4.64.0"
vidgear = "^0.2.5"
openpyxl = "^3.0.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
