[tool.poetry]
name = "soccertrack"
version = "0.1.0"
description = "A dataset and algorithm for multi-object tracking in sports"
authors = ["Atom Scott <atom.james.scott@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
omegaconf = "^2.2.2"
pytest = "^7.1.2"
ffmpeg-python = "^0.2.0"
numpy = "^1.22.4"
pandas = "^1.4.2"

[tool.poetry.dev-dependencies]
prospector = "^1.7.7"
mypy = "^0.960"
pyroma = "^4.0"
types-python-dateutil = "^2.8.17"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
